---

- hosts: docker-servers
  become: true

  tasks:
          - name: Add Docker repo
            get_url:
             url: https://download.docker.com/linux/centos/docker-ce.repo
             dest: /etc/yum.repos.d/docker-ce.repo

          - name: Install containerd.io
            dnf:
             name: 'https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm'
             state: present
           
          - name: Install docker-ce
            dnf:
             name: docker-ce
             state: present
          
          - name: Install python Docker Module
            pip:
                    name: docker

          - name: Add user to docker group
            user:
                    name: ivan
                    groups: docker
                    append: yes

          - name: Enable and start docker daemon
            service:
             name: docker
             state: started
             enabled: true

          - name: Copy Site Contents to Remote Dir
            shell: mkdir /tmp/temp-directory-101 ;wget 172.16.1.10/site.zip -O /tmp/temp-directory-101/site.zip; unzip /tmp/temp-directory-101/site.zip 

          - name: Creating the Container
            docker_container:
                    name: nginx_container
                    image: nginx:latest
                    state: started
                    published_ports: 8080:80
                    volumes:
                            - "/home/ivan/site:/usr/share/nginx/html:ro"
                    detach: yes

          - name: Add docker0 to trusted Firewalld zone
            shell: firewall-cmd --add-interface docker0 --zone trusted --permanent; firewall-cmd --reload


          - name: Add ports to Firewalld
            firewalld:
             port: 8080/tcp
             permanent: yes
             immediate: yes
             state: enabled
